### ISSUE TITLE
README modification to cover PR

### ISSUE THREAD

**Issue by drchangliu** [OU-CS3560/examples#6]
Modify the README.md file to reflect the fact that this repo is also used for students to practice git pull requests.

**Comment by brandonlwharton** [comment]
bw368216

**Comment by TylerZwolenik** [comment]
fixed issue #6 #36

**Comment by grant-madden** [comment]
Resolved this issue in PR #74

**Comment by GmcgeeCodes** [comment]
Resolved the issue

**Comment by krerkkiat** [comment]
Close since this is for quiz.
